language: node_js
node_js:
  - 12
services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed truonghet/udagram-api-feed
  - docker tag udagram-api-user truonghet/udagram-api-user
  - docker tag udagram-frontend truonghet/udagram-frontend
  - docker tag reverseproxy truonghet/reverseproxy
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push truonghet/udagram-api-feed
  - docker push truonghet/udagram-api-user
  - docker push truonghet/udagram-frontend
  - docker push truonghet/reverseproxy
